# PWM Example Makefile

# Project name
PROJECT := pwm

# Source files
SRCS = \
	main.c \
	pwm_driver.c

# Drivers used (adds drivers directory to VPATH)
DRIVERS = pwm_driver.c

# Include common Makefile
include ../shared/common.mk
