# GPIO Example Makefile

# Project name
PROJECT := gpio

# Source files
SRCS = \
	main.c \
	gpio_driver.c

# Drivers used (adds drivers directory to VPATH)
DRIVERS = gpio_driver.c

# Include common Makefile
include ../shared/common.mk
