# GPIO interrupt example: button (GPIO input) toggles LED (GPIO output) via external IRQ

PROJECT := gpio-int
USE_STDLIB := 0

SRCS := main.c gpio_driver.c util.c
DRIVERS := gpio_driver.c
VPATH += $(BSP_SHARED)

include ../shared/common.mk
