# I2C Example Makefile

# Project name
PROJECT := i2c-transfer

# Bare-metal: no libc
USE_STDLIB := 0

# Source files
SRCS = \
	main.c \
	i2c_driver.c

# Drivers used (adds drivers directory to VPATH)
DRIVERS = i2c_driver.c

# Include common Makefile
include ../shared/common.mk
